
stages:
  - security-scan

secret_detection_job:
  stage: security-scan
  image: 
    name: zricethezav/gitleaks:latest
    entrypoint: [""]
  script:
    - gitleaks detect --source . --verbose --redact
  tags:
    - docker