name: DevSecOps-Pipeline

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy SCA scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'app/'
          format: 'json'
          output: 'trivy-results.json'
          severity: 'CRITICAL,HIGH'

      - name: Upload results to DefectDojo
        if: always()
        env:
          DD_URL: ${{ secrets.DEFECTDOJO_URL }}
          DD_TOKEN: ${{ secrets.DEFECTDOJO_TOKEN }}
        run: |
          curl -k -L -X POST "${DD_URL}/reimport-scan/" \
            -H "Authorization: Token ${DD_TOKEN}" \
            -H "ngrok-skip-browser-warning: true" \
            -F "active=true" \
            -F "verified=true" \
            -F "scan_type=Trivy Scan" \
            -F "product_name=GitHub-Sucure CI/CD" \
            -F "engagement_name=CI-CD-Pipeline" \
            -F "file=@trivy-results.json" \
            -F "scan_date=$(date +%Y-%m-%d)" \
            -F "minimum_severity=Info" \
            -F "close_old_findings=true" \
            -o response.txt -w "%{http_code}" || true
          
          echo "Server Response Status: $(cat response.txt)"
          cat response.txt
  

  secret-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Run Gitleaks
        run: |
          docker run -v ${{ github.workspace }}:/path zricethezav/gitleaks:latest detect \
            --source="/path" \
            --no-git \
            -v \
            --report-format json \
            --report-path="/path/gitleaks-report.json" || echo "Secrets found or scan issue"

      - name: Upload Gitleaks report to DefectDojo
        if: always()
        env:
          DD_URL: ${{ secrets.DEFECTDOJO_URL }}
          DD_TOKEN: ${{ secrets.DEFECTDOJO_TOKEN }}
        run: |
          
          curl -k -L -X POST "${DD_URL}/reimport-scan/" \
            -H "Authorization: Token ${DD_TOKEN}" \
            -H "ngrok-skip-browser-warning: true" \
            -F "active=true" \
            -F "verified=true" \
            -F "scan_type=Gitleaks Scan" \
            -F "product_name=GitHub-Sucure CI/CD" \
            -F "engagement_name=CI-CD-Pipeline" \
            -F "file=@gitleaks-report.json" \
            -F "scan_date=$(date +%Y-%m-%d)" \
            -F "minimum_severity=Info" \
            -F "close_old_findings=true"
  
  
  sast-semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep
        run: |
          docker run -v ${{ github.workspace }}:/src returntocorp/semgrep semgrep scan \
            --config="p/python" \
            --json \
            --output=/src/semgrep-report.json || echo "Issues found"

      - name: Upload Semgrep report to DefectDojo
        if: always()
        env:
          DD_URL: ${{ secrets.DEFECTDOJO_URL }}
          DD_TOKEN: ${{ secrets.DEFECTDOJO_TOKEN }}
        run: |
          curl -k -L -X POST "${DD_URL}/reimport-scan/" \
            -H "Authorization: Token ${DD_TOKEN}" \
            -H "ngrok-skip-browser-warning: true" \
            -F "active=true" \
            -F "verified=true" \
            -F "scan_type=Semgrep JSON Report" \
            -F "product_name=GitHub-Sucure CI/CD" \
            -F "engagement_name=CI-CD-Pipeline" \
            -F "file=@semgrep-report.json" \
            -F "scan_date=$(date +%Y-%m-%d)" \
            -F "minimum_severity=Info" \
            -F "close_old_findings=true"

  # ---------------------------------------------------
  # ЭТАП KUBESEC (K8s SAST)
  # ---------------------------------------------------
  sast-kubesec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Kubesec
        run: |
          docker run -i kubesec/kubesec:v2 scan /dev/stdin < k8s/deployment.yaml > k8s/kubesec-report.json || echo "Issues found"

      - name: Upload Kubesec report to DefectDojo
        if: always()
        env:
          DD_URL: ${{ secrets.DEFECTDOJO_URL }}
          DD_TOKEN: ${{ secrets.DEFECTDOJO_TOKEN }}
        run: |
          curl -k -L -X POST "${DD_URL}/import-scan/" \
            -H "Authorization: Token ${DD_TOKEN}" \
            -H "ngrok-skip-browser-warning: true" \
            -F "active=true" \
            -F "verified=true" \
            -F "scan_type=Kubeaudit Scan" \
            -F "product_name=GitHub-Sucure CI/CD" \
            -F "engagement_name=CI-CD-Pipeline" \
            -F "file=@k8s/kubesec-report.json" \
            -F "scan_date=$(date +%Y-%m-%d)" \
            -F "minimum_severity=Info" \
            -F "close_old_findings=true"

  dast-zap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and Run App
        run: |
          pip install -r app/requirements.txt
          python app/app.py & 
          sleep 10

      - name: Prepare Workspace
        run: |
          touch $(pwd)/report_xml.xml
          chmod 777 $(pwd)/report_xml.xml
          chmod 777 $(pwd)

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:5000'
          cmd_options: '-x report_xml.xml'
          fail_action: false
          allow_issue_writing: false

      - name: Upload ZAP Report to DefectDojo
        if: always()
        env:
          DD_URL: ${{ secrets.DEFECTDOJO_URL }}
          DD_TOKEN: ${{ secrets.DEFECTDOJO_TOKEN }}
        run: |
          if [ -f "report_xml.xml" ]; then
            echo "Report found, uploading to DefectDojo..."
            curl -k -L -X POST "${DD_URL}/reimport-scan/" \
              -H "Authorization: Token ${DD_TOKEN}" \
              -H "ngrok-skip-browser-warning: true" \
              -F "active=true" \
              -F "verified=true" \
              -F "scan_type=ZAP Scan" \
              -F "product_name=GitHub-Sucure CI/CD" \
              -F "engagement_name=CI-CD-Pipeline" \
              -F "file=@report_xml.xml" \
              -F "scan_date=$(date +%Y-%m-%d)" \
              -F "minimum_severity=Info" \
              -F "close_old_findings=true"
          else
            echo "Error: report_xml.xml not found. Check ZAP logs above."
            ls -la
          fi
  
  # ---------------------------------------------------
  # ЭТАП CONTAINER SCANNING (Trivy)
  # ---------------------------------------------------
  container-security:
    runs-on: ubuntu-latest
    needs: [sast-semgrep, secret-detection] # Запускаем после статики
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          # Собираем образ с тегом 'finenomore:test'
          # Убедись, что Dockerfile находится в папке app/ или в корне
          docker build -t finenomore:test -f app/Dockerfile . 

      - name: Run Trivy Image Scan
        run: |
          # Сканируем собранный образ и сохраняем результат в JSON
          docker run -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}:/root/.cache/ \
            aquasec/trivy:latest image \
            --format json \
            --output /root/.cache/trivy-image-report.json \
            finenomore:test

      - name: Upload Trivy Image Report to DefectDojo
        if: always()
        env:
          DD_URL: ${{ secrets.DEFECTDOJO_URL }}
          DD_TOKEN: ${{ secrets.DEFECTDOJO_TOKEN }}
        run: |
          curl -k -L -X POST "${DD_URL}/import-scan/" \
            -H "Authorization: Token ${DD_TOKEN}" \
            -H "ngrok-skip-browser-warning: true" \
            -F "active=true" \
            -F "verified=true" \
            -F "scan_type=Trivy Scan" \
            -F "product_name=GitHub-Sucure CI/CD" \
            -F "engagement_name=CI-CD-Pipeline" \
            -F "file=@trivy-image-report.json" \
            -F "scan_date=$(date +%Y-%m-%d)" \
            -F "minimum_severity=Low" \
            -F "close_old_findings=true"