name: DevSecOps-Pipeline

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy SCA scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'app/'
          format: 'json'
          output: 'trivy-results.json'
          severity: 'CRITICAL,HIGH'

      # 2. Загружаем результаты в DefectDojo
      - name: Upload results to DefectDojo
        if: always()
        env:
          DD_URL: ${{ secrets.DEFECTDOJO_URL }}
          DD_TOKEN: ${{ secrets.DEFECTDOJO_TOKEN }}
        run: |
          # 1. Удаляем завершающий слеш из URL, если он там есть
          CLEAN_BASE_URL="${DD_URL%/}"
          
          # 2. Формируем финальную строку
          FINAL_URL="${CLEAN_BASE_URL}/import-scan/"
          
          # 3. Выводим FINAL_URL в лог (GitHub сам заменит секретную часть на ***)
          # Это поможет нам увидеть, не превратился ли URL в кашу
          echo "Target URL: $FINAL_URL"
          
          # 4. Выполняем запрос
          curl -v -g -X POST "$FINAL_URL" \
          -H "Authorization: Token $DD_TOKEN" \
          -H "ngrok-skip-browser-warning: true" \
          -F "active=true" \
          -F "verified=true" \
          -F "scan_type=Trivy Scan" \
          -F "product_id=${{ secrets.DEFECTDOJO_PRODUCT_ID }}" \
          -F "engagement_name=GitHub-Scan-${{ github.run_id }}" \
          -F "file=@trivy-results.json"


