name: Security Scan

# Запускать при каждом пуше в ветку main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  secret-detection:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Скачиваем код репозитория
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Важно: скачиваем всю историю коммитов для проверки

      # Шаг 2: Запускаем Gitleaks
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Мы специально НЕ ставим 'continue-on-error', чтобы пайплайн упал
